### ISSUE TITLE
Please add howto leave interaction mode in the help list.

### ISSUE THREAD

**Issue by jokergaming** [felixonmars/ydcv#33]
As you can see, when I type ydcv in my terminal, it just get into the interaction mode. But the problem is
when I'm in interaction mode, I type a world and get the meaning, but I try to type CTRL-C, I can't quit
I have to type CTRL-Z to suspend. I think @felixonmars should write the method in the help list or the README file.

**Comment by samsun639** [comment]
Use Ctrl+d to terminate.




On 07/03/2017 09:34, jokergaming wrote:

As you can see, when I type ydcv in my terminal, it just get into the interaction mode. But the problem is
when I'm in interaction mode, I type a world and get the meaning, but I try to type CTRL-C, I can't quit
I have to type CTRL-Z to suspend. I think @felixonmars should write the method in the help list.
